### PR TITLE
Julia v1.3 support

### LINKED ISSUE #5: Testy not compatible at the moment with julia 1.3
Error:

```
ERROR: LoadError: type Regex has no field match_data
Stacktrace:
 [1] getproperty(::Any, ::Symbol) at ./Base.jl:20
 [2] pmatch(::Regex, ::String, ::Int64, ::UInt32) at /home/rbvermaa/.julia/packages/Testy/wVZqX/src/Testy.jl:26
 [3] pmatch(::Regex, ::String, ::Int64) at /home/rbvermaa/.julia/packages/Testy/wVZqX/src/Testy.jl:23
 [4] pmatch(::Regex, ::String) at /home/rbvermaa/.julia/packages/Testy/wVZqX/src/Testy.jl:40
 [5] top-level scope at /home/rbvermaa/.julia/packages/Testy/wVZqX/src/Testy.jl:113
 [6] include at ./boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1094
 [8] include(::Module, ::String) at ./Base.jl:31
 [9] include(::String) at ./client.jl:432
 [10] top-level scope at none:5
in expression starting at /....../.julia/packages/Testy/wVZqX/test/runtests.jl:53
ERROR: Package Testy errored during testing
```

The `match_data` property was removed in JuliaLang/julia#32381

### PR DESCRIPTION
**Pull request by ghost**
Fix Testy's regex modifications to work in Julia versions >= `v1.3`, and maintain support for older versions.

Also enables Travis testing so that we can verify that it's working on all those separate julia versions. :)

This basically applies the changes in https://github.com/JuliaLang/julia/pull/32381 to this package.

Fixes https://github.com/RelationalAI-oss/Testy.jl/issues/5

### CODE REVIEW

File: src/Testy.jl [hunk 1]
```diff
@@ -3,38 +3,73 @@ module Testy
...
     Base.compile(re)
     opts = re.match_options | add_opts
-    # rc == -1 means no match, -2 means partial match.
-    rc = pexec(re.regex, str, idx-1, opts, re.match_data)
-    if rc == -1 || (rc == -2 && (re.match_options & Base.PCRE.PARTIAL_HARD) == 0)
-        return nothing
+    @static if VERSION >= v"1.3-"
+        # rc == -1 means no match, -2 means partial match.
+        rc, data = pexec_r_data(re.regex, str, idx-1, opts)
+        if rc == -1 || (rc == -2 && (re.match_options & Base.PCRE.PARTIAL_HARD) == 0)
```
Comment (ghost) [inline src/Testy.jl]: @tjgreen Shouldn't this be checking `opts` instead of `re.match_options` for `PARTIAL_HARD`? If the user adds `PARTIAL_HARD` in the `add_opts`, it looks like that gets passed-through and should be used in this return value?

**Comment by ghost** [comment]
Also, while I was looking at this, after a touch of refactoring, i think if we wanted to merge this partial matching w/ Julia, it's just this one-line change:

https://github.com/JuliaLang/julia/compare/master...NHDaly:nhdaly-regex-partial-match

EDIT: I've opened JuliaLang/julia#33646 with the regex changes described above after @tjgreen's approval. 🙂

**Comment by rai-nhdaly** [comment]
(i've opened https://github.com/JuliaLang/julia/pull/33646 with the regex changes described above after @tjgreen's approval. 🙂)

**Comment by ghost** [comment]
I've added tests specific to the regex behavior. I'm going to merge this once Travis returns green.
